version: "3.6"

services:
  db:
    container_name: rails_tutorial_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample_app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql

  web:
    container_name: rails_tutorial_web
    build: ./
    volumes:
      - ./src:/sample_app
    ports:
      - "3000:3000"
    depends_on:
      - db
