version: "3.6"

services:
  db:
    container_name: rails_tutorial_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data

  web:
    container_name: rails_tutorial_web
    build: ./
    volumes:
      - ./src:/sample_app
    ports:
      - "3000:3000"
    depends_on:
      - db
