# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c30ccc2dc25af0f5d13a522c3c0c5cdd1944e2f69a341e7095dc3ba99674cee3eb4f32c757efd97aaf04cacfc38854ab94d7de6def0134ca152a8676e8ec510f

test:
  secret_key_base: 44cb944d8103449555bfedf84c6c82f9c690a8ab874c02eb83fc88811368c71522da7658ada3cc16f9e995c6dc44e93ead3931e0b4a78cc7e3cb5398b9587ce0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
